<?php
return [
    // 基础库。
    'edubase' => [
        // 基础块。
        'jc_channels' => [
            'database' => 'edubase',
            'string' => 'bc_channels',
            'object' => null,
            'introduction' => '渠道表',
        ],
        'jc_config_reason_types' => [
            'database' => 'edubase',
            'string' => 'bc_config_reason_types',
            'object' => ConfigReasonTypesModel::class,
            'introduction' => '系统原因类型表',
        ],
        'jc_expense_types' => [
            'database' => 'edubase',
            'string' => 'bc_expense_types',
            'object' => null,
            'introduction' => '支出类型表',
        ],
        'jc_merchant_types' => [
            'database' => 'edubase',
            'string' => 'mc_merchant_types',
            'object' => null,
            'introduction' => '商家类型表',
        ],
        'jc_labels' => [
            'database' => 'edubase',
            'string' => 'gc_labels',
            'object' => null,
            'introduction' => '商家标签表',
        ],
        'jc_label_types' => [
            'database' => 'edubase',
            'string' => 'gc_label_types',
            'object' => null,
            'introduction' => '标签类型表',
        ],
        'jc_label_types' => [
            'database' => 'edubase',
            'string' => 'gc_label_types',
            'object' => null,
            'introduction' => '标签类型表',
        ],
        'jc_financial_banks' => [
            'database' => 'edubase',
            'string' => 'mc_financial_banks',
            'object' => null,
            'introduction' => '银行表',
        ],
        'jc_sync_sites' => [
            'database' => 'edubase',
            'string' => 'mc_sync_sites',
            'object' => null,
            'introduction' => '同步登录站点信息表',
        ],
        'jc_areas' => [
            'database' => 'edubase',
            'string' => 'uc_areas',
            'object' => AreaModel::class,
            'introduction' => '地区表',
        ],
        'jc_ad_spaces' => [
            'database' => 'edubase',
            'string' => 'at_cms_ad_space',
            'object' => null,
            'introduction' => '广告位表',
        ],
        'jc_publish_settings' => [
            'database' => 'edubase',
            'string' => 'at_cms_publish_setting',
            'object' => null,
            'introduction' => '站点发布点设置表',
        ],
        'jc_site_settings' => [
            'database' => 'edubase',
            'string' => 'at_cms_site_setting',
            'object' => null,
            'introduction' => '站点设置表',
        ],
        'jc_tpl_files' => [
            'database' => 'edubase',
            'string' => 'at_cms_template_file',
            'object' => null,
            'introduction' => '模板文件表',
        ],
        'jc_tpl_types' => [
            'database' => 'edubase',
            'string' => 'at_cms_template_type',
            'object' => null,
            'introduction' => '模版类型表',
        ],
        'jc_discounts' => [
            'database' => 'edubase',
            'string' => 'bc_discounts',
            'object' => null,
            'introduction' => '优惠表',
        ],
        'jc_class_comment_datas' => [
            'database' => 'edubase',
            'string' => 'gc_class_comment_datas',
            'object' => null,
            'introduction' => '班级评论数据表',
        ],
        'jc_categories' => [
            'database' => 'edubase',
            'string' => 'gc_categories',
            'object' => null,
            'introduction' => '类别表',
        ],
        'jc_types' => [
            'database' => 'edubase',
            'string' => 'gc_types',
            'object' => null,
            'introduction' => '商品类型表',
        ],
        'jc_moods' => [
            'database' => 'edubase',
            'string' => 'at_cms_mood',
            'object' => null,
            'introduction' => '表情表',
        ],
        'jc_states' => [
            'database' => 'edubase',
            'string' => 'sc_states',
            'object' => null,
            'introduction' => '国籍表',
        ],

        // 配置块。
        'pz_ali_informations' => [
            'database' => 'edubase',
            'string' => 'bc_ali_informations',
            'object' => null,
            'introduction' => '支付宝信息',
        ],
        'pz_app_labels' => [
            'database' => 'edubase',
            'string' => 'bc_app_labels',
            'object' => null,
            'introduction' => 'APP标签表',
        ],
        'pz_app_merchants' => [
            'database' => 'edubase',
            'string' => 'bc_app_merchants',
            'object' => null,
            'introduction' => '商家APP表',
        ],
        'pz_app_modules' => [
            'database' => 'edubase',
            'string' => 'bc_app_modules',
            'object' => null,
            'introduction' => 'APP业务模块表',
        ],
        'pz_app_plugins' => [
            'database' => 'edubase',
            'string' => 'bc_app_plugins',
            'object' => null,
            'introduction' => 'APP插件表',
        ],
        'pz_app_template_confs' => [
            'database' => 'edubase',
            'string' => 'bc_app_template_confs',
            'object' => null,
            'introduction' => 'APP模板配置表',
        ],
        'pz_app_templates' => [
            'database' => 'edubase',
            'string' => 'bc_app_templates',
            'object' => null,
            'introduction' => 'APP模板表',
        ],
        'pz_menu_modules' => [
            'database' => 'edubase',
            'string' => 'mc_menu_module',
            'object' => null,
            'introduction' => '菜单模块关系表',
        ],
        'pz_menus' => [
            'database' => 'edubase',
            'string' => 'mc_menus',
            'object' => MenuModel::class,
            'introduction' => '菜单表',
        ],
        'pz_modules' => [
            'database' => 'edubase',
            'string' => 'mc_modules',
            'object' => null,
            'introduction' => '模块表',
        ],
        'pz_platform_menus' => [
            'database' => 'edubase',
            'string' => 'mc_platform_menu',
            'object' => null,
            'introduction' => '平台菜单关系表',
        ],
        'pz_platform_versions' => [
            'database' => 'edubase',
            'string' => 'mc_platform_versions',
            'object' => PlatformVersionsModel::class,
            'introduction' => '平台版本表',
        ],
        'pz_pricing_structures' => [
            'database' => 'edubase',
            'string' => 'mc_pricing_structures',
            'object' => null,
            'introduction' => '价格体系表',
        ],
        'pz_template_prices' => [
            'database' => 'edubase',
            'string' => 'mc_template_prices',
            'object' => null,
            'introduction' => '模板价格表',
        ],
        'pz_code_version_modules' => [
            'database' => 'edubase',
            'string' => 'sc_platform_code_version_module',
            'object' => null,
            'introduction' => '平台代码版本和模块关系表',
        ],
        'pz_code_versions' => [
            'database' => 'edubase',
            'string' => 'sc_platform_code_versions',
            'object' => null,
            'introduction' => '平台代码版本表',
        ],

        // 系统权限块。
        'xtqx_admins' => [
            'database' => 'edubase',
            'string' => 'ec_admins',
            'object' => AdminModel::class,
            'introduction' => 'Admin表',
        ],
        'xtqx_platform_roles' => [
            'database' => 'edubase',
            'string' => 'sc_platform_roles',
            'object' => null,
            'introduction' => '平台角色表',
        ],
        'xtqx_tokens' => [
            'database' => 'edubase',
            'string' => 'sc_tokens',
            'object' => TokenModel::class,
            'introduction' => '令牌表',
        ],
        'xtqx_user_roles' => [
            'database' => 'edubase',
            'string' => 'sc_user_roles',
            'object' => null,
            'introduction' => '用户角色表',
        ],
        'xtqx_users' => [
            'database' => 'edubase',
            'string' => 'sc_users',
            'object' => null,
            'introduction' => '用户表',
        ],

        // 商品块。
        'sp_activity_templates' => [
            'database' => 'edubase',
            'string' => 'gc_activity_templates',
            'object' => null,
            'introduction' => '活动模板表',
        ],
        'sp_platforms' => [
            'database' => 'edubase',
            'string' => 'mc_platforms',
            'object' => PlatformsModel::class,
            'introduction' => '平台表',
        ],
        'sp_attributes' => [
            'database' => 'edubase',
            'string' => 'gc_goods_attributes',
            'object' => null,
            'introduction' => '商品属性表',
        ],
        'sp_prices' => [
            'database' => 'edubase',
            'string' => 'gc_goods_prices',
            'object' => null,
            'introduction' => '商品价格表',
        ],

        // 会员块。
        'hy_merchants' => [
            'database' => 'edubase',
            'string' => 'mc_merchants',
            'object' => MerchantModel::class,
            'introduction' => '商家表',
        ],
        'hy_member_externs' => [
            'database' => 'edubase',
            'string' => 'mc_member_extern',
            'object' => McMemberExternModel::class,
            'introduction' => '会员与第三方平台用户关系表',
        ],
        'hy_members' => [
            'database' => 'edubase',
            'string' => 'mc_members',
            'object' => MemberModel::class,
            'introduction' => '会员表',
        ],
        'hy_parent_collections' => [
            'database' => 'edubase',
            'string' => 'bc_parent_collections',
            'object' => null,
            'introduction' => '家长收藏商品和机构表',
        ],
        'hy_parent_students' => [
            'database' => 'edubase',
            'string' => 'uc_parent_student',
            'object' => ParentStudentModel::class,
            'introduction' => '家长学员关系表',
        ],
        'hy_parents' => [
            'database' => 'edubase',
            'string' => 'uc_parents',
            'object' => ParentModel::class,
            'introduction' => '家长表',
        ],
        'hy_students' => [
            'database' => 'edubase',
            'string' => 'uc_students',
            'object' => StudentsModel::class,
            'introduction' => '学员表',
        ],

        // 会员订单块。
        'hydd_app_applies' => [
            'database' => 'edubase',
            'string' => 'bc_app_apply',
            'object' => null,
            'introduction' => 'APP申请表',
        ],
        'hydd_merchant_shopping_carts' => [
            'database' => 'edubase',
            'string' => 'bc_merchant_shopping_carts',
            'object' => null,
            'introduction' => '商家购物车表',
        ],
        'hydd_merchant_buy_platforms' => [
            'database' => 'edubase',
            'string' => 'mc_merchant_buy_platform',
            'object' => null,
            'introduction' => '商家平台购买信息表',
        ],
        'hydd_merchant_orders' => [
            'database' => 'edubase',
            'string' => 'mc_merchant_orders',
            'object' => null,
            'introduction' => '商家订单表',
        ],
        'hydd_merchant_platforms' => [
            'database' => 'edubase',
            'string' => 'mc_merchant_platforms',
            'object' => null,
            'introduction' => '商家授权平台关系表',
        ],
        'hydd_merchant_withdraw_recharges' => [
            'database' => 'edubase',
            'string' => 'mc_merchant_withdraw_recharges',
            'object' => null,
            'introduction' => '商家网商提现充值表',
        ],
        'hydd_merchant_withdraws' => [
            'database' => 'edubase',
            'string' => 'mc_merchant_withdraws',
            'object' => null,
            'introduction' => '商家网商提现表',
        ],
        'hydd_employee_distributions' => [
            'database' => 'edubase',
            'string' => 'employee_account_record_detail_distributions',
            'object' => EmployeeAccountRecordDetailDistributionsModel::class,
            'introduction' => '分销提现详情',
        ],
        'hydd_employee_clues' => [
            'database' => 'edubase',
            'string' => 'employee_account_record_detail_order_clues',
            'object' => null,
            'introduction' => '员工财务账户记录详情线索购买【出账】表',
        ],
        'us_recharge_distributions' => [
            'database' => 'eduwork',
            'string' => 'parent_account_record_detail_recharge_distributions',
            'object' => null,
            'introduction' => '账户【进账】记录详情-分销提成详情表',
        ],
        'yh_distribution_records' => [
            'database' => 'eduwork',
            'string' => 'bc_distribution_user_goods_records',
            'object' => null,
            'introduction' => '用户和商品分销的提成记录',
        ],
        'hydd_employee_rewards' => [
            'database' => 'edubase',
            'string' => 'employee_account_record_detail_order_rewards',
            'object' => null,
            'introduction' => '员工财务账户记录详情打赏【出账】表',
        ],
        'hydd_employee_withdraws' => [
            'database' => 'edubase',
            'string' => 'employee_account_record_detail_order_withdraw',
            'object' => null,
            'introduction' => '员工财务记录详情订单【出账】-提现详情表',
        ],
        'hydd_employee_orders' => [
            'database' => 'edubase',
            'string' => 'employee_account_record_detail_orders',
            'object' => null,
            'introduction' => '员工财务记录详情订单【出账】表',
        ],
        'hydd_employee_recharge_clues' => [
            'database' => 'edubase',
            'string' => 'employee_account_record_detail_recharge_clues',
            'object' => null,
            'introduction' => '员工财务账户记录详情线索被购买【进账】表',
        ],
        'hydd_employee_recharge_onlines' => [
            'database' => 'edubase',
            'string' => 'employee_account_record_detail_recharge_onlines',
            'object' => null,
            'introduction' => '员工财务记录详情充值【进账】-在线充值【支付宝、网银】详情表',
        ],
        'hydd_employee_recharge_rewards' => [
            'database' => 'edubase',
            'string' => 'employee_account_record_detail_recharge_rewards',
            'object' => null,
            'introduction' => '员工财务账户记录详情打赏【进账】表',
        ],
        'hydd_employee_recharges' => [
            'database' => 'edubase',
            'string' => 'employee_account_record_detail_recharges',
            'object' => null,
            'introduction' => '员工财务账户记录详情充值【进账】表',
        ],
        'hydd_merchant_apps' => [
            'database' => 'edubase',
            'string' => 'merchant_account_record_detail_order_apps',
            'object' => MerchantAccountRecordDetailOrderAppModel::class,
            'introduction' => '商家财务记录详情订单【出账】-应用详情表',
        ],
        'hydd_merchant_app_services' => [
            'database' => 'edubase',
            'string' => 'merchant_account_record_detail_order_app_services',
            'object' => MerchantAccountRecordDetailOrderAppServiceModel::class,
            'introduction' => '商家应用服务表',
        ],
        'hydd_merchant_sms' => [
            'database' => 'edubase',
            'string' => 'merchant_account_record_detail_order_sms',
            'object' => null,
            'introduction' => '商家财务记录详情订单【出账】-短信详情表',
        ],
        'hydd_merchant_templates' => [
            'database' => 'edubase',
            'string' => 'merchant_account_record_detail_order_templates',
            'object' => null,
            'introduction' => '商家财务记录详情订单【出账】-模板详情表',
        ],
        'hydd_merchant_order_withdraw' => [
            'database' => 'edubase',
            'string' => 'merchant_account_record_detail_order_withdraw',
            'object' => null,
            'introduction' => '商家财务记录详情订单【出账】-提现详情表',
        ],
        'hydd_merchant_detail_orders' => [
            'database' => 'edubase',
            'string' => 'merchant_account_record_detail_orders',
            'object' => MerchantAccountRecordDetailOrdersModel::class,
            'introduction' => '商家财务记录详情订单【出账】表',
        ],
        'hydd_merchant_recharge_onlines' => [
            'database' => 'edubase',
            'string' => 'merchant_account_record_detail_recharge_onlines',
            'object' => null,
            'introduction' => '商家务记录详情充值【进账】-在线充值【支付宝，网银】详情表',
        ],
        'hydd_merchant_recharge_overclasses' => [
            'database' => 'edubase',
            'string' => 'merchant_account_record_detail_recharge_overclasses',
            'object' => null,
            'introduction' => '商家财务记录详情充值【进账】-班级结课详情表',
        ],
        'hydd_merchant_recharges' => [
            'database' => 'edubase',
            'string' => 'merchant_account_record_detail_recharges',
            'object' => null,
            'introduction' => '商家财务账户记录详情充值【进账】表',
        ],
        'hydd_merchant_againsignups' => [
            'database' => 'edubase',
            'string' => 'merchant_account_record_detail_recharge_againsignups',
            'object' => null,
            'introduction' => '商商家财务记录详情充值【进账】-续报一次性结算详情表',
        ],
        // 会员账户块。
        'hyzh_bankcards' => [
            'database' => 'edubase',
            'string' => 'mc_bankcard',
            'object' => null,
            'introduction' => '银行卡表',
        ],
        'hyzh_withdraw_applys' => [
            'database' => 'edubase',
            'string' => 'mc_withdraw_applys',
            'object' => null,
            'introduction' => '提现申请表',
        ],
        'hyzh_employee_account_records' => [
            'database' => 'edubase',
            'string' => 'employee_account_records',
            'object' => null,
            'introduction' => '员工账户记录表',
        ],
        'hyzh_employee_accounts' => [
            'database' => 'edubase',
            'string' => 'employee_accounts',
            'object' => null,
            'introduction' => '员工财务账户表',
        ],
        'hyzh_employee_banks' => [
            'database' => 'edubase',
            'string' => 'employee_banks',
            'object' => null,
            'introduction' => '会员【员工】绑定银行卡关系表',
        ],
        'hyzh_merchant_account_records' => [
            'database' => 'edubase',
            'string' => 'merchant_account_records',
            'object' => null,
            'introduction' => '商家账户记录表',
        ],
        'hyzh_merchant_accounts' => [
            'database' => 'edubase',
            'string' => 'merchant_accounts',
            'object' => null,
            'introduction' => '商家财务账户表',
        ],
        'hyzh_merchant_banks' => [
            'database' => 'edubase',
            'string' => 'merchant_banks',
            'object' => null,
            'introduction' => '商家绑定银行卡关系表',
        ],
        'hyzh_bankcard_binds' => [
            'database' => 'edubase',
            'string' => 'pay_bankcard_binds',
            'object' => null,
            'introduction' => '支付中心-绑定银行卡',
        ],
        'hyzh_pay_logs' => [
            'database' => 'edubase',
            'string' => 'pay_logs',
            'object' => null,
            'introduction' => '支付中心-支付日志表',
        ],
        'hyzh_withdraw_orders' => [
            'database' => 'edubase',
            'string' => 'pay_withdraw_orders',
            'object' => null,
            'introduction' => '支付中心-提现订单表',
        ],
        'hyzh_parent_records' => [
            'database' => 'edubase',
            'string' => 'parent_account_records',
            'object' => ParentAccountRecordsModel::class,
            'introduction' => '家长账户记录表',
        ],
        'hyzh_parent_accounts' => [
            'database' => 'edubase',
            'string' => 'parent_accounts',
            'object' => ParentAccountsModel::class,
            'introduction' => '家长报哪好账户表',
        ],
        'hyzh_parent_banks' => [
            'database' => 'edubase',
            'string' => 'parent_banks',
            'object' => null,
            'introduction' => '家长绑定银行卡关系表',
        ],

        // 业务配置块。
        'ywpz_app_merchant_base_confs' => [
            'database' => 'edubase',
            'string' => 'bc_app_merchant_base_confs',
            'object' => null,
            'introduction' => '商家APP基础配置表',
        ],
        'ywpz_app_merchant_confs' => [
            'database' => 'edubase',
            'string' => 'bc_app_merchant_confs',
            'object' => null,
            'introduction' => '商家APP配置表',
        ],
        'ywpz_app_merchant_packs' => [
            'database' => 'edubase',
            'string' => 'bc_app_merchant_packs',
            'object' => null,
            'introduction' => '商家APP打包记录表',
        ],
        'ywpz_app_merchant_use_template_logs' => [
            'database' => 'edubase',
            'string' => 'bc_app_merchant_use_template_logs',
            'object' => null,
            'introduction' => '商家APP使用模板历史记录',
        ],
        'ywpz_mc_platform_merchant_domain' => [
            'database' => 'edubase',
            'string' => 'mc_platform_merchant_domain',
            'object' => McPlatformMerchantDomainModel::class,
            'introduction' => '商家转班配置表',
        ],

        // 优惠块。
        'yh_platform_coupon_releases' => [
            'database' => 'edubase',
            'string' => 'bc_platform_coupon_releases',
            'object' => null,
            'introduction' => '报哪好平台优惠券发放记录',
        ],
        'yh_platform_coupons' => [
            'database' => 'edubase',
            'string' => 'bc_platform_coupons',
            'object' => null,
            'introduction' => '报哪好平台优惠券',
        ],

        // 线索块。
        'xs_platform_trials' => [
            'database' => 'edubase',
            'string' => 'bc_platform_trials',
            'object' => null,
            'introduction' => '平台试用表',
        ],
        'xs_merchant_clues' => [
            'database' => 'edubase',
            'string' => 'mc_merchant_clues',
            'object' => null,
            'introduction' => '商家线索表',
        ],
        'xs_member_source_statistics' => [
            'database' => 'edubase',
            'string' => 'bi_member_source_statistics',
            'object' => null,
            'introduction' => '教务宝试用用户来源统计',
        ],
        'xs_register' => [
            'database' => 'edubase',
            'string' => 'at_cms_lx_register',
            'object' => null,
            'introduction' => '申请注册的功能需求',
        ],

        // 文章内容块。
        'wznr_article_categories' => [
            'database' => 'edubase',
            'string' => 'mc_baonahao_article_categories',
            'object' => null,
            'introduction' => '报哪好文章分类表',
        ],
        'wznr_articles' => [
            'database' => 'edubase',
            'string' => 'mc_baonahao_articles',
            'object' => null,
            'introduction' => '报哪好文章表',
        ],
        'wznr_index_carousels' => [
            'database' => 'edubase',
            'string' => 'mc_baonahao_index_carousels',
            'object' => null,
            'introduction' => '报哪好首页轮播图',
        ],
        'wznr_index_hotwords' => [
            'database' => 'edubase',
            'string' => 'mc_baonahao_index_hotwords',
            'object' => null,
            'introduction' => '报哪好热门词',
        ],
        'wznr_notices' => [
            'database' => 'edubase',
            'string' => 'sc_notices',
            'object' => null,
            'introduction' => '系统公告表',
        ],

        // 数据块。
        'sj_feedbacks' => [
            'database' => 'edubase',
            'string' => 'mc_feedbacks',
            'object' => null,
            'introduction' => '反馈表',
        ],
        'sj_guide_relations' => [
            'database' => 'edubase',
            'string' => 'mc_guide_relations',
            'object' => null,
            'introduction' => '应用倒流关系表',
        ],
        'sj_merchant_feedbacks' => [
            'database' => 'edubase',
            'string' => 'mc_merchant_feedbacks',
            'object' => null,
            'introduction' => '商家意见反馈表',
        ],
        'sj_merchant_sms_consumes' => [
            'database' => 'edubase',
            'string' => 'mc_merchant_sms_consume',
            'object' => null,
            'introduction' => '短信消耗记录表',
        ],
        'sj_operation_platforms' => [
            'database' => 'edubase',
            'string' => 'mc_operation_platform',
            'object' => null,
            'introduction' => '运营指标平台关系表',
        ],
        'sj_operation_targets' => [
            'database' => 'edubase',
            'string' => 'mc_operation_targets',
            'object' => null,
            'introduction' => '运营指标表',
        ],
        'sj_kpi_details' => [
            'database' => 'edubase',
            'string' => 'sc_platform_project_kpi_details',
            'object' => null,
            'introduction' => '平台项目KPI详情',
        ],
        'sj_kpis' => [
            'database' => 'edubase',
            'string' => 'sc_platform_project_kpis',
            'object' => null,
            'introduction' => '平台项目KPI',
        ],
        'sj_goods_numbers' => [
            'database' => 'edubase',
            'string' => 'gc_district_goods_numbers',
            'object' => null,
            'introduction' => '所在地区课程数',
        ],
        'sj_parent_feedbacks' => [
            'database' => 'edubase',
            'string' => 'uc_parent_feedbacks',
            'object' => null,
            'introduction' => '家长意见反馈表',
        ],
        'sh_kpi_statistics' => [
            'database' => 'edubase',
            'string' => 'tmp_kpi_statistics',
            'object' => null,
            'introduction' => '临时表-KIP统计',
        ],

        // 日志块。
        'rz_withdraw_apply_logs' => [
            'database' => 'edubase',
            'string' => 'sc_withdraw_apply_logs',
            'object' => null,
            'introduction' => '提现申请记录日志表',
        ],
    ],

    // 业务库。
    'eduwork' => [
        // 基础数据。
        'jcsj_finance_bodys' => [
            'database' => 'eduwork',
            'string' => 'bc_finance_bodys',
            'object' => FinanceBodyModel::class,
            'introduction' => '财务主体表',
        ],
        'jcsj_merchant_brands' => [
            'database' => 'eduwork',
            'string' => 'bc_merchant_brands',
            'object' => null,
            'introduction' => '商家品牌表',
        ],
        'jcsj_campus' => [
            'database' => 'eduwork',
            'string' => 'gc_campus',
            'object' => CampusModel::class,
            'introduction' => '校区表',
        ],
        'jcsj_campus_imgs' => [
            'database' => 'eduwork',
            'string' => 'gc_campus_imgs',
            'object' => null,
            'introduction' => '分校图片表',
        ],
        'jcsj_classrooms' => [
            'database' => 'eduwork',
            'string' => 'gc_classrooms',
            'object' => ClassRoomsModel::class,
            'introduction' => '基础配置-教室表',
        ],
        'jcsj_ad_data' => [
            'database' => 'eduwork',
            'string' => 'at_cms_ad_data',
            'object' => null,
            'introduction' => '广告位数据表',
        ],
        'jcsj_categories' => [
            'database' => 'eduwork',
            'string' => 'at_cms_category',
            'object' => null,
            'introduction' => '栏目表',
        ],
        'jcsj_comments' => [
            'database' => 'eduwork',
            'string' => 'at_cms_comment',
            'object' => null,
            'introduction' => '评论表',
        ],
        'jcsj_contacts' => [
            'database' => 'eduwork',
            'string' => 'at_cms_contact',
            'object' => null,
            'introduction' => '站点联系人',
        ],
        'jcsj_links' => [
            'database' => 'eduwork',
            'string' => 'at_cms_link',
            'object' => null,
            'introduction' => '友情链接表',
        ],
        'jcsj_news' => [
            'database' => 'eduwork',
            'string' => 'at_cms_news',
            'object' => null,
            'introduction' => '新闻表',
        ],
        'jcsj_mn_messages' => [
            'database' => 'eduwork',
            'string' => 'mini_messages',
            'object' => null,
            'introduction' => '迷你营销消息表',
        ],
        'jcsj_attachments' => [
            'database' => 'eduwork',
            'string' => 'at_cms_attachment',
            'object' => null,
            'introduction' => '附件表',
        ],
        'jcsj_attachment_indexs' => [
            'database' => 'eduwork',
            'string' => 'at_cms_attachment_index',
            'object' => null,
            'introduction' => '附件引用表',
        ],
        'jcsj_collection_nodes' => [
            'database' => 'eduwork',
            'string' => 'at_cms_collection_node',
            'object' => null,
            'introduction' => '收集节点表',
        ],
        'jcsj_pictures' => [
            'database' => 'eduwork',
            'string' => 'at_cms_picture',
            'object' => null,
            'introduction' => '图片表',
        ],
        'jcsj_app_article_labels' => [
            'database' => 'eduwork',
            'string' => 'bc_app_article_labels',
            'object' => null,
            'introduction' => 'APP商家文章咨询标签表',
        ],
        'jcsj_app_articles' => [
            'database' => 'eduwork',
            'string' => 'bc_app_articles',
            'object' => null,
            'introduction' => 'APP文章咨询表',
        ],
        'jcsj_state_schools' => [
            'database' => 'eduwork',
            'string' => 'bc_state_schools',
            'object' => StateSchoolModel::class,
            'introduction' => '公立校表',
        ],
        'jcsj_merchant_imgs' => [
            'database' => 'eduwork',
            'string' => 'mc_merchant_imgs',
            'object' => null,
            'introduction' => '商家图片表',
        ],
        'jcsj_cms_downloads' => [
            'database' => 'eduwork',
            'string' => 'at_cms_download',
            'object' => null,
            'introduction' => 'CMS 下载表',
        ],
        'jcsj_cms_download_datas' => [
            'database' => 'eduwork',
            'string' => 'at_cms_download_data',
            'object' => null,
            'introduction' => '下载数据表',
        ],
        'jcsj_zs_attachments' => [
            'database' => 'eduwork',
            'string' => '17zs_attachment',
            'object' => null,
            'introduction' => '17招生附件表',
        ],
        'jcsj_zs_categories' => [
            'database' => 'eduwork',
            'string' => '17zs_category',
            'object' => null,
            'introduction' => '17招生栏目表',
        ],
        'jcsj_zs_pictures' => [
            'database' => 'eduwork',
            'string' => '17zs_picture',
            'object' => null,
            'introduction' => '17招生图片库表',
        ],
        'jcsj_mn_posters' => [
            'database' => 'eduwork',
            'string' => 'mini_posters',
            'object' => null,
            'introduction' => '迷你营销海报',
        ],
        'jcsj_mn_poster_contents' => [
            'database' => 'eduwork',
            'string' => 'mini_poster_contents',
            'object' => null,
            'introduction' => '迷你营销海报内容',
        ],

        // 业务配置。
        'ywpz_service_types' => [
            'database' => 'eduwork',
            'string' => 'bc_finance_body_service_types',
            'object' => null,
            'introduction' => '财务主体与服务类型关系表',
        ],
        'ywpz_categoryies_service_types' => [
            'database' => 'eduwork',
            'string' => 'bc_finance_categories_service_types',
            'object' => CategoryServiceTypeModel::class,
            'introduction' => '分类对应服务类型表',
        ],
        'ywpz_service_type_logs' => [
            'database' => 'eduwork',
            'string' => 'bc_finance_category_service_type_logs',
            'object' => CategoryServiceTypeLogModel::class,
            'introduction' => '学科分类和服务类型配置日志',
        ],
        'ywpz_invoice_service_types' => [
            'database' => 'eduwork',
            'string' => 'bc_finance_invoice_service_types',
            'object' => InvoiceServiceTypeModel::class,
            'introduction' => '发票服务类型',
        ],
        'ywpz_channel_relations' => [
            'database' => 'eduwork',
            'string' => 'bc_merchant_channel_relations',
            'object' => null,
            'introduction' => '商家渠道关系表',
        ],
        'ywpz_league_auths' => [
            'database' => 'eduwork',
            'string' => 'bc_merchant_league_auths',
            'object' => null,
            'introduction' => '商家加盟授权表',
        ],
        'ywpz_leagues' => [
            'database' => 'eduwork',
            'string' => 'bc_merchant_leagues',
            'object' => MerchantLeagueModel::class,
            'introduction' => '商家加盟表',
        ],
        'ywpz_material_brochures' => [
            'database' => 'eduwork',
            'string' => 'bc_merchant_material_brochures',
            'object' => null,
            'introduction' => '招生简章素材',
        ],
        'ywpz_material_imgs' => [
            'database' => 'eduwork',
            'string' => 'bc_merchant_material_imgs',
            'object' => null,
            'introduction' => '图片素材',
        ],
        'ywpz_material_parameters' => [
            'database' => 'eduwork',
            'string' => 'bc_merchant_material_parameters',
            'object' => null,
            'introduction' => '参数表',
        ],
        'ywpz_material_syllabus' => [
            'database' => 'eduwork',
            'string' => 'bc_merchant_material_syllabus',
            'object' => null,
            'introduction' => '教学大纲素材',
        ],
        'ywpz_parent_rules' => [
            'database' => 'eduwork',
            'string' => 'bc_point_merchant_parent_rules',
            'object' => PointMerchantParentRuleModel::class,
            'introduction' => '商家家长积分配置表',
        ],
        'ywpz_messages' => [
            'database' => 'eduwork',
            'string' => 'mc_messages',
            'object' => null,
            'introduction' => '消息表',
        ],
        'ywpz_category_merchants' => [
            'database' => 'eduwork',
            'string' => 'gc_category_merchants',
            'object' => CategoryMerchantModel::class,
            'introduction' => '类别表-商家商品分类',
        ],
        'ywpz_category_realias' => [
            'database' => 'eduwork',
            'string' => 'gc_category_realias',
            'object' => GoodsCategoryRealiasModel::class,
            'introduction' => '商品分类表',
        ],
        'ywpz_class_type_categories' => [
            'database' => 'eduwork',
            'string' => 'gc_class_type_categories',
            'object' => ClassTypeCategoryModel::class,
            'introduction' => '班型分类关系表',
        ],
        'ywpz_class_types' => [
            'database' => 'eduwork',
            'string' => 'gc_class_types',
            'object' => ClassTypeModel::class,
            'introduction' => '班型表',
        ],
        'ywpz_subject_levels' => [
            'database' => 'eduwork',
            'string' => 'gc_subject_levels',
            'object' => null,
            'introduction' => '学科级别',
        ],
        'ywpz_textbook_versions' => [
            'database' => 'eduwork',
            'string' => 'gc_textbook_versions',
            'object' => TextbookVersionModel::class,
            'introduction' => '教材版本表',
        ],
        'ywpz_activity_types' => [
            'database' => 'eduwork',
            'string' => 'mc_activity_types',
            'object' => null,
            'introduction' => '活动类型表',
        ],
        'ywpz_basic_configs' => [
            'database' => 'eduwork',
            'string' => 'mc_basic_configs',
            'object' => null,
            'introduction' => '基础项配置表',
        ],
        'ywpz_communicate_type_ands' => [
            'database' => 'eduwork',
            'string' => 'mc_communicate_type_ands',
            'object' => null,
            'introduction' => '沟通形式&意向学科表',
        ],
        'ywpz_enroll_intentions' => [
            'database' => 'eduwork',
            'string' => 'mc_enroll_intentions',
            'object' => null,
            'introduction' => '报读意向表',
        ],
        'ywpz_teacher_grades' => [
            'database' => 'eduwork',
            'string' => 'mc_teacher_grades',
            'object' => null,
            'introduction' => '教师等级表',
        ],
        'ywpz_mnwx_menus' => [
            'database' => 'eduwork',
            'string' => 'mini_weixin_menus',
            'object' => null,
            'introduction' => '迷你营销微信菜单表',
        ],
        'ywpz_config_merchant_accounts' => [
            'database' => 'eduwork',
            'string' => 'bc_config_merchant_accounts',
            'object' => ConfigMerchantAccountsModel::class,
            'introduction' => '商家账户配置表',
        ],
        'ywpz_config_merchant_data_masking' => [
            'database' => 'eduwork',
            'string' => 'bc_config_merchant_data_masking',
            'object' => ConfigMerchantDataMaskingModel::class,
            'introduction' => '商家原因配置表',
        ],
        'ywpz_config_merchant_reasons' => [
            'database' => 'eduwork',
            'string' => 'bc_config_merchant_reasons',
            'object' => ConfigMerchantReasonModel::class,
            'introduction' => '商家原因配置表',
        ],
        'ywpz_config_merchant_recharge_details' => [
            'database' => 'eduwork',
            'string' => 'bc_config_merchant_recharge_details',
            'object' => ConfigMerchantRechargeDetails::class,
            'introduction' => '商家账户充值赠送阶梯详情表',
        ],
        'ywpz_config_merchant_refunds' => [
            'database' => 'eduwork',
            'string' => 'bc_config_merchant_refunds',
            'object' => ConfigMerchantRefundModel::class,
            'introduction' => '商家退费规则配置表',
        ],
        'ywpz_config_purchase_agreements' => [
            'database' => 'eduwork',
            'string' => 'bc_config_purchase_agreements',
            'object' => PurchaseAgreementModel::class,
            'introduction' => '购买协议表',
        ],
        'ywpz_config_merchant_signup' => [
            'database' => 'eduwork',
            'string' => 'bc_config_merchant_signup',
            'object' => ConfigMerchantSignupModel::class,
            'introduction' => '报名配置',
        ],
        'ywpz_config_merchant_signup_details' => [
            'database' => 'eduwork',
            'string' => 'bc_config_merchant_signup_details',
            'object' => ConfigMerchantSignupDetailsModel::class,
            'introduction' => '报名配置-详情',
        ],
        'ywpz_config_merchant_attendances' => [
            'database' => 'eduwork',
            'string' => 'bc_config_merchant_attendances',
            'object' => ConfigMerchantAttendancesModel::class,
            'introduction' => '考勤配置表',
        ],
        'ywpz_config_merchant_signature' => [
            'database' => 'eduwork',
            'string' => 'bc_config_merchant_signatures',
            'object' => ConfigMerchantSignatureModel::class,
            'introduction' => '家长签名设置',
        ],
        'ywpz_tms_signups' => [
            'database' => 'eduwork',
            'string' => 'bc_config_tms_jiaowubao_signups',
            'object' => null,
            'introduction' => '商家业务管理平台-教务宝报名配置表',
        ],
        'ywpz_config_merchant_signup_rolls' => [
            'database' => 'eduwork',
            'string' => 'bc_config_merchant_signup_rolls',
            'object' => ConfigMerchantSignupRollModel::class,
            'introduction' => '报名配置-艺体课',
        ],
        'ywpz_config_merchant_contract_rolls' => [
            'database' => 'eduwork',
            'string' => 'bc_config_merchant_contract_rolls',
            'object' => ConfigMerchantContractRollModel::class,
            'introduction' => '报名配置-艺体课',
        ],
        'ywpz_merchant_weixins' => [
            'database' => 'eduwork',
            'string' => 'mc_merchant_weixins',
            'object' => null,
            'introduction' => '商家微信号表',
        ],
        'ywpz_grades' => [
            'database' => 'eduwork',
            'string' => 'gc_grades',
            'object' => GradeModel::class,
            'introduction' => '年部年级表',
        ],
        'ywpz_parameters' => [
            'database' => 'eduwork',
            'string' => 'mc_parameters',
            'object' => null,
            'introduction' => '系统参数设置表',
        ],
        'ywpz_classification_ands' => [
            'database' => 'eduwork',
            'string' => 'mc_classification_ands',
            'object' => null,
            'introduction' => '资源分类&渠道来源表',
        ],
        'ywpz_holiday' => [
            'database' => 'eduwork',
            'string' => 'bc_holiday',
            'object' => BcHolidayModel::class,
            'introduction' => '停课日表',
        ],
        'ywpz_merchant_refund_qrz_rate' => [
            'database' => 'eduwork',
            'string' => 'bc_config_merchant_refund_qrz_rates',
            'object' => MerchantRefundQrzRateModel::class,
            'introduction' => '全日制商家退费服务费率',
        ],
        'ywpz_merchant_service_fee_qrz' => [
            'database' => 'eduwork',
            'string' => 'bc_config_merchant_service_fee_qrzs',
            'object' => MerchantServiceFeeQrzModel::class,
            'introduction' => '全日制商家退费服务费率',
        ],

        // 退班退费。
        'tbtf_refund_apply_details' => [
            'database' => 'eduwork',
            'string' => 'bc_finance_parent_refund_apply_details',
            'object' => FinanceParentRefundApplyDetailsModel::class,
            'introduction' => '家长退费申请记录详情表',
        ],
        'tbtf_refund_apply_review_logs' => [
            'database' => 'eduwork',
            'string' => 'bc_finance_parent_refund_apply_review_logs',
            'object' => FinanceParentRefundApplyReviewLogsModel::class,
            'introduction' => '家长退费申请审核日志表',
        ],
        'tbtf_refund_applys' => [
            'database' => 'eduwork',
            'string' => 'bc_finance_parent_refund_applys',
            'object' => FinanceParentRefundApplysModel::class,
            'introduction' => '家长退费申请记录表',
        ],
        'tbtf_refund_logs' => [
            'database' => 'eduwork',
            'string' => 'bc_order_refund_logs',
            'object' => null,
            'introduction' => '退费日志表',
        ],
        'tbtf_cash_refunds' => [
            'database' => 'eduwork',
            'string' => 'fc_cash_refunds',
            'object' => null,
            'introduction' => '现金退费表',
        ],

        // 学员。
        'xy_communicates' => [
            'database' => 'eduwork',
            'string' => 'bc_student_communicates',
            'object' => null,
            'introduction' => '意向客户沟通记录表',
        ],

        // 商品。
        'sp_output_record_details' => [
            'database' => 'eduwork',
            'string' => 'bc_goods_output_record_details',
            'object' => GoodsOutputRecordDetailsModel::class,
            'introduction' => '商品出库记录详情表',
        ],
        'sp_output_records' => [
            'database' => 'eduwork',
            'string' => 'bc_goods_output_records',
            'object' => GoodsOutputRecordsModel::class,
            'introduction' => '商品出库记录表',
        ],
        'sp_stock_records' => [
            'database' => 'eduwork',
            'string' => 'bc_goods_stock_records',
            'object' => GoodsStockRecordsModel::class,
            'introduction' => '商品库存操作(包括:报损、退库)',
        ],
        'sp_transfer_records' => [
            'database' => 'eduwork',
            'string' => 'bc_goods_transfer_records',
            'object' => GoodsTransferRecordsModel::class,
            'introduction' => '商品调拨表',
        ],
        'sp_campus_goods_stocks' => [
            'database' => 'eduwork',
            'string' => 'gc_campus_goods_stocks',
            'object' => CampusGoodsStocksModel::class,
            'introduction' => '校区商品库存表',
        ],
        'sp_course_rolls' => [
            'database' => 'eduwork',
            'string' => 'gc_course_rolls',
            'object' => CourseRollModel::class,
            'introduction' => '课程【滚动班】表',
        ],
        'sp_courses' => [
            'database' => 'eduwork',
            'string' => 'gc_courses',
            'object' => CourseModel::class,
            'introduction' => '课程表',
        ],
        'sp_course_type' => [
            'database' => 'eduwork',
            'string' => 'gc_course_types',
            'object' => CourseTypeModel::class,
            'introduction' => '课程类型表',
        ],
        'sp_courses_lessons' => [
            'database' => 'eduwork',
            'string' => 'gc_courses_lessons',
            'object' => CourseLessonModel::class,
            'introduction' => '课程课次表',
        ],
        'sp_goods' => [
            'database' => 'eduwork',
            'string' => 'gc_goods',
            'object' => GoodsModel::class,
            'introduction' => '商品表',
        ],
        'sp_attachments' => [
            'database' => 'eduwork',
            'string' => 'gc_goods_attachments',
            'object' => null,
            'introduction' => '商品附属商品表',
        ],
        'sp_class_otms' => [
            'database' => 'eduwork',
            'string' => 'gc_goods_class_otms',
            'object' => GoodsClassOtmModel::class,
            'introduction' => '商品【小班】表',
        ],
        'sp_class_oto_courses' => [
            'database' => 'eduwork',
            'string' => 'gc_goods_class_oto_courses',
            'object' => GoodsClassOtoCourseModel::class,
            'introduction' => '商品【大班】课程模板表',
        ],
        'sp_otos' => [
            'database' => 'eduwork',
            'string' => 'gc_goods_class_otos',
            'object' => GoodsClassOtoModel::class,
            'introduction' => '商品【大班】表',
        ],
        'sp_rolls' => [
            'database' => 'eduwork',
            'string' => 'gc_goods_class_rolls',
            'object' => GoodsClassRollModel::class,
            'introduction' => '班级【滚动班】表',
        ],
        'sp_goods_imgs' => [
            'database' => 'eduwork',
            'string' => 'gc_goods_imgs',
            'object' => null,
            'introduction' => '商品图片表',
        ],
        'sp_goods_realias' => [
            'database' => 'eduwork',
            'string' => 'gc_goods_realias',
            'object' => GoodsRealiasModel::class,
            'introduction' => '商品【教学用品】表',
        ],
        'sp_lesson_rolls' => [
            'database' => 'eduwork',
            'string' => 'gc_lesson_rolls',
            'object' => LessonRollModel::class,
            'introduction' => '课次【滚动班】表',
        ],
        'sp_lessons' => [
            'database' => 'eduwork',
            'string' => 'gc_lessons',
            'object' => LessonsModel::class,
            'introduction' => '课次表',
        ],
        'sp_oto_courses' => [
            'database' => 'eduwork',
            'string' => 'gc_oto_courses',
            'object' => null,
            'introduction' => '一对一课程表（以分类为单位逐条存储）',
        ],
        'sp_oto_courses_sons' => [
            'database' => 'eduwork',
            'string' => 'gc_oto_courses_sons',
            'object' => null,
            'introduction' => '一对一课程表子表（存储分类对应的价格体系）',
        ],
        'sp_course_lives' => [
            'database' => 'eduwork',
            'string' => 'gc_course_lives',
            'object' => null,
            'introduction' => '课程【云课堂直播】表',
        ],
        'sp_course_lesson_lives' => [
            'database' => 'eduwork',
            'string' => 'gc_course_lesson_lives',
            'object' => null,
            'introduction' => '课程课次【云课堂直播】表',
        ],
        'sp_goods_class_lives' => [
            'database' => 'eduwork',
            'string' => 'gc_goods_class_lives',
            'object' => null,
            'introduction' => '班级【云课堂直播】表',
        ],
        'sp_lesson_lives' => [
            'database' => 'eduwork',
            'string' => 'gc_lesson_lives',
            'object' => null,
            'introduction' => '班级课次【云课堂直播】表',
        ],
        'sp_course_lives_unitprices' => [
            'database' => 'eduwork',
            'string' => 'gc_course_lives_unitprices',
            'object' => null,
            'introduction' => '单元课时单价【云课堂直播】表',
        ],
        'sp_student_schools' => [
            'database' => 'eduwork',
            'string' => 'mc_student_schools',
            'object' => null,
            'introduction' => '生源校表',
        ],
        'sp_business_data_extern' => [
            'database' => 'eduwork',
            'string' => 'mc_business_data_extern',
            'object' => McBusinessDataExternModel::class,
            'introduction' => '第三方业务数据关联表'
        ],
        'sp_merchant_extern' => [
            'database' => 'edubase',
            'string' => 'mc_merchant_extern',
            'object' => McMerchantExternModel::class,
            'introduction' => '第三方机构关联表'
        ],

        // 订单
        'dd_invoice_orders' => [
            'database' => 'eduwork',
            'string' => 'bc_finance_invoice_orders',
            'object' => null,
            'introduction' => '发票与订单关系表',
        ],
        'dd_invoices' => [
            'database' => 'eduwork',
            'string' => 'bc_finance_invoices',
            'object' => FinanceInvoicesModel::class,
            'introduction' => '发票表',
        ],
        'dd_otms_pay_records' => [
            'database' => 'eduwork',
            'string' => 'bc_order_class_otms_pay_records',
            'object' => null,
            'introduction' => '一对多班级订单支付记录表',
        ],
        'dd_shopping_carts' => [
            'database' => 'eduwork',
            'string' => 'bc_parent_shopping_carts',
            'object' => null,
            'introduction' => '家长购物车表',
        ],
        'dd_parent_accounts' => [
            'database' => 'eduwork',
            'string' => 'parent_account_record_detail_order_accounts',
            'object' => ParentAccountRecordDetailOrderAccountsModel::class,
            'introduction' => '家长账户订单详情表',
        ],
        'dd_parent_activities' => [
            'database' => 'eduwork',
            'string' => 'parent_account_record_detail_order_activities',
            'object' => null,
            'introduction' => '订单详情表【活动详情】',
        ],
        'dd_parent_class_otm_discounts' => [
            'database' => 'eduwork',
            'string' => 'parent_account_record_detail_order_class_otm_discounts',
            'object' => null,
            'introduction' => '订单优惠方案关系表',
        ],
        'dd_parent_class_otm_packages' => [
            'database' => 'eduwork',
            'string' => 'parent_account_record_detail_order_class_otm_packages',
            'object' => ParentAccountRecordDetailOrderClassOtmPackagesModel::class,
            'introduction' => '订单详情表【小班套餐】',
        ],
        'dd_parent_class_otms' => [
            'database' => 'eduwork',
            'string' => 'parent_account_record_detail_order_class_otms',
            'object' => ParentAccountRecordDetailOrderClassOtmsModel::class,
            'introduction' => '订单详情表【报名详情】',
        ],
        'dd_parent_class_otos' => [
            'database' => 'eduwork',
            'string' => 'parent_account_record_detail_order_class_otos',
            'object' => ParentAccountRecordDetailOrderClassOtosModel::class,
            'introduction' => '订单详情表【大班详情】',
        ],
        'dd_parent_class_rolls' => [
            'database' => 'eduwork',
            'string' => 'parent_account_record_detail_order_class_rolls',
            'object' => ParentAccountRecordDetailOrderClassRollModel::class,
            'introduction' => '订单详情表【班级-滚动班报名详情】',
        ],
        'dd_parent_course_rolls' => [
            'database' => 'eduwork',
            'string' => 'parent_account_record_detail_order_course_rolls',
            'object' => ParentAccountRecordDetailOrderCourseRollModel::class,
            'introduction' => '订单详情表【课程-滚动班课程详情】',
        ],
        'dd_parent_discount_buygifts' => [
            'database' => 'eduwork',
            'string' => 'parent_account_record_detail_order_discount_buygifts',
            'object' => null,
            'introduction' => '账户【出账】记录详情-订单优惠-买赠优惠表',
        ],
        'dd_parent_discount_nowminus' => [
            'database' => 'eduwork',
            'string' => 'parent_account_record_detail_order_discount_nowminus',
            'object' => null,
            'introduction' => '账户【出账】记录详情-订单优惠-立减优惠表',
        ],
        'dd_parent_discount_oldwithnews' => [
            'database' => 'eduwork',
            'string' => 'parent_account_record_detail_order_discount_oldwithnews',
            'object' => null,
            'introduction' => '账户【出账】记录详情-订单优惠-老带新优惠表',
        ],
        'dd_parent_discount_rebates' => [
            'database' => 'eduwork',
            'string' => 'parent_account_record_detail_order_discount_rebates',
            'object' => null,
            'introduction' => '账户【出账】记录详情-订单优惠-折扣优惠表',
        ],
        'dd_parent_discount_timelimitsignups' => [
            'database' => 'eduwork',
            'string' => 'parent_account_record_detail_order_discount_timelimitsignups',
            'object' => null,
            'introduction' => '账户【出账】记录详情-订单优惠-限时抢报优惠表',
        ],
        'dd_parent_discount' => [
            'database' => 'eduwork',
            'string' => 'parent_account_record_detail_order_discounts',
            'object' => ParentAccountRecordDetailOrderDiscountModel::class,
            'introduction' => '账户【出账】记录详情-订单优惠主表',
        ],
        'dd_parent_merges' => [
            'database' => 'eduwork',
            'string' => 'parent_account_record_detail_order_merges',
            'object' => null,
            'introduction' => '合并订单支付表',
        ],
        'dd_parent_repays' => [
            'database' => 'eduwork',
            'string' => 'parent_account_record_detail_order_repays',
            'object' => ParentAccountRecordDetailOrderRepayModel::class,
            'introduction' => '订单补缴记录',
        ],
        'dd_parent_textbook_refund_records' => [
            'database' => 'eduwork',
            'string' => 'parent_account_record_detail_order_textbook_refund_records',
            'object' => ParentAccountRecordDetailOrderTextbooksRefundRecordsModel::class,
            'introduction' => '商品退货记录表',
        ],
        'dd_parent_textbooks' => [
            'database' => 'eduwork',
            'string' => 'parent_account_record_detail_order_textbooks',
            'object' => ParentAccountRecordDetailOrderTextbooksModel::class,
            'introduction' => '财务记录详情订单【出账】-教材详情表',
        ],
        'dd_parent_virtual_class_hour_packages' => [
            'database' => 'eduwork',
            'string' => 'parent_account_record_detail_order_virtual_class_hour_packages',
            'object' => null,
            'introduction' => '订单详情表【买课时包详情】',
        ],
        'dd_parent_virtuals' => [
            'database' => 'eduwork',
            'string' => 'parent_account_record_detail_order_virtuals',
            'object' => ParentAccountRecordDetailOrderVirtualsModel::class,
            'introduction' => '订单详情表【购买虚拟商品】',
        ],
        'dd_parent_withdraws' => [
            'database' => 'eduwork',
            'string' => 'parent_account_record_detail_order_withdraw',
            'object' => ParentAccountRecordDetailOrderWithdrawModel::class,
            'introduction' => '家长财务记录详情订单【出账】-提现详情表',
        ],
        'dd_parent_orders' => [
            'database' => 'eduwork',
            'string' => 'parent_account_record_detail_orders',
            'object' => ParentAccountRecordDetailOrderModel::class,
            'introduction' => '账户【出账】记录详情',
        ],
        'dd_parent_class_lives' => [
            'database' => 'eduwork',
            'string' => 'parent_account_record_detail_order_class_lives',
            'object' => null,
            'introduction' => '订单详情表【班级-云课堂直播】',
        ],
        'dd_parent_course_lives' => [
            'database' => 'eduwork',
            'string' => 'parent_account_record_detail_order_course_lives',
            'object' => null,
            'introduction' => '订单详情表【课程-云课堂直播】',
        ],

        // 人事。
        'rs_distributors' => [
            'database' => 'eduwork',
            'string' => 'mc_distributors',
            'object' => null,
            'introduction' => '会员商家分销关系表',
        ],
        'rs_emp_data_permissions' => [
            'database' => 'eduwork',
            'string' => 'mc_employee_data_permissions',
            'object' => null,
            'introduction' => '员工数据权限表',
        ],
        'rs_emp_data_roles' => [
            'database' => 'eduwork',
            'string' => 'mc_employee_data_roles',
            'object' => null,
            'introduction' => '员工数据角色表',
        ],
        'rs_emp_roles' => [
            'database' => 'eduwork',
            'string' => 'mc_employee_role',
            'object' => EmployeeRoleModel::class,
            'introduction' => '员工角色/岗位关系表',
        ],
        'rs_emp_shortcuts' => [
            'database' => 'eduwork',
            'string' => 'mc_employee_shortcuts',
            'object' => EmployeeShortcutsModel::class,
            'introduction' => '员工快速入口模块表',
        ],
        'rs_emp_teachers' => [
            'database' => 'eduwork',
            'string' => 'mc_employee_teachers',
            'object' => EmployeeTeacherModel::class,
            'introduction' => '员工教师扩展表',
        ],
        'rs_emps' => [
            'database' => 'eduwork',
            'string' => 'mc_employees',
            'object' => EmployeeModel::class,
            'introduction' => '员工表',
        ],
        'rs_emp_depts' => [
            'database' => 'eduwork',
            'string' => 'mc_merchant_departments',
            'object' => MerchantDepartmentModel::class,
            'introduction' => '商家部门表',
        ],
        'rs_emp_teacher_timetables' => [
            'database' => 'eduwork',
            'string' => 'mc_employee_teacher_timetables',
            'object' => null,
            'introduction' => '教师可排课【云课堂直播】表',
        ],
        'rs_emp_teacher_timetables_details' => [
            'database' => 'eduwork',
            'string' => 'mc_employee_teacher_timetables_details',
            'object' => null,
            'introduction' => '教师时间详情【云课堂直播】表',
        ],
        'rs_platform_roles' => [
            'database' => 'eduwork',
            'string' => 'mc_platform_roles',
            'object' => PlatformRolesModel::class,
            'introduction' => '商家平台角色表',
        ],
        'rs_micro_cards' => [
            'database' => 'eduwork',
            'string' => 'mini_micro_card',
            'object' => null,
            'introduction' => '迷你营销微名片表',
        ],

        // 优惠。
        'yh_moresignups' => [
            'database' => 'eduwork',
            'string' => 'bc_discount_merchant_plan_moresignups',
            'object' => null,
            'introduction' => '商家优惠方案-多科连报详情表',
        ],
        'yh_oldwithnews' => [
            'database' => 'eduwork',
            'string' => 'bc_discount_merchant_plan_oldwithnews',
            'object' => null,
            'introduction' => '商家优惠方案-老带新详情表',
        ],
        'yh_plans' => [
            'database' => 'eduwork',
            'string' => 'bc_discount_merchant_plans',
            'object' => null,
            'introduction' => '商家优惠方案-主体表',
        ],
        'yh_discount_merchants' => [
            'database' => 'eduwork',
            'string' => 'bc_discount_merchants',
            'object' => null,
            'introduction' => '优惠商家关系表',
        ],
        'yh_goods_marketings' => [
            'database' => 'eduwork',
            'string' => 'bc_goods_marketings',
            'object' => null,
            'introduction' => '商品营销表',
        ],
        'yh_goods_union_discounts' => [
            'database' => 'eduwork',
            'string' => 'bc_goods_union_discounts',
            'object' => null,
            'introduction' => '班级联合报名优惠表（双十二）',
        ],
        'yh_coupons' => [
            'database' => 'eduwork',
            'string' => 'uc_coupons',
            'object' => null,
            'introduction' => '家长优惠券表',
        ],
        'yh_hour_packages' => [
            'database' => 'eduwork',
            'string' => 'gc_goods_class_hour_packages',
            'object' => GoodsClassHourPackagesModel::class,
            'introduction' => '商品【课时包】表',
        ],
        'yh_otm_packages' => [
            'database' => 'eduwork',
            'string' => 'gc_goods_class_otm_packages',
            'object' => null,
            'introduction' => '班级【小班】套餐',
        ],
        'yh_discount_plans' => [
            'database' => 'eduwork',
            'string' => 'gc_goods_discount_plans',
            'object' => null,
            'introduction' => '商品优惠方案关系表',
        ],

        // 用户。
        'us_homework_answers' => [
            'database' => 'eduwork',
            'string' => 'bc_homework_answers',
            'object' => null,
            'introduction' => '学生作业完成情况表',
        ],
        'us_homework_bases' => [
            'database' => 'eduwork',
            'string' => 'bc_homework_bases',
            'object' => null,
            'introduction' => '家庭作业主表',
        ],
        'us_homework_imgs' => [
            'database' => 'eduwork',
            'string' => 'bc_homework_imgs',
            'object' => null,
            'introduction' => '家庭作业图片表(与bc_homework_bases或bc_homework_answers为多对一关系)',
        ],
        'us_parent_records' => [
            'database' => 'eduwork',
            'string' => 'bc_point_merchant_parent_records',
            'object' => PointMerchantParentRecordModel::class,
            'introduction' => '商家家长积分记录表',
        ],
        'us_student_exams' => [
            'database' => 'eduwork',
            'string' => 'bc_student_exam_results',
            'object' => StudentExamResultModel::class,
            'introduction' => '商家学员考试成绩表',
        ],
        'us_teach_comments' => [
            'database' => 'eduwork',
            'string' => 'gc_comments',
            'object' => CommentsModel::class,
            'introduction' => '家长/学员对教学评论表',
        ],
        'us_learn_comments' => [
            'database' => 'eduwork',
            'string' => 'uc_comments',
            'object' => null,
            'introduction' => '教师对学员学习情况评论表',
        ],
        'us_im_messages' => [
            'database' => 'eduwork',
            'string' => 'uc_im_message',
            'object' => null,
            'introduction' => '即时通讯消息',
        ],
        'us_otms_browse_records' => [
            'database' => 'eduwork',
            'string' => 'uc_goods_class_otms_browse_records',
            'object' => null,
            'introduction' => '一对多班级商品浏览记录',
        ],
        'us_merchant_records' => [
            'database' => 'eduwork',
            'string' => 'parent_account_merchant_records',
            'object' => ParentAccountMerchantRecordsModel::class,
            'introduction' => '商家家长账户记录表',
        ],
        'us_merchants' => [
            'database' => 'eduwork',
            'string' => 'parent_account_merchants',
            'object' => ParentAccountMerchantsModel::class,
            'introduction' => '家长机构账户表',
        ],
        'us_recharge_alipays' => [
            'database' => 'eduwork',
            'string' => 'parent_account_record_detail_recharge_alipays',
            'object' => ParentAccountRecordDetailRechargeAlipaysModel::class,
            'introduction' => '账户【进账】记录详情-线下充值【支付宝】详情表',
        ],
        'us_recharge_banktransfers' => [
            'database' => 'eduwork',
            'string' => 'parent_account_record_detail_recharge_banktransfers',
            'object' => ParentAccountRecordDetailRechargeBanktransfersModel::class,
            'introduction' => '账户【进账】记录详情-线下充值【银行转帐】详情表',
        ],
        'us_mrecharge_cashs' => [
            'database' => 'eduwork',
            'string' => 'parent_account_record_detail_recharge_cashs',
            'object' => ParentAccountRecordDetailRechargeCashModel::class,
            'introduction' => '账户【进账】记录详情-线下充值【现金】详情表',
        ],
        'us_recharge_cheques' => [
            'database' => 'eduwork',
            'string' => 'parent_account_record_detail_recharge_cheques',
            'object' => ParentAccountRecordDetailRechargeChequesModel::class,
            'introduction' => '账户【进账】记录详情-线下充值【支票】详情表',
        ],
        'us_recharge_merchant_accounts' => [
            'database' => 'eduwork',
            'string' => 'parent_account_record_detail_recharge_merchant_accounts',
            'object' => ParentAccountRecordDetailRechargeMerchantAccountsModel::class,
            'introduction' => '账户【进账】记录详情-线下充值【家长商家账户】详情表',
        ],
        'us_recharge_onlines' => [
            'database' => 'eduwork',
            'string' => 'parent_account_record_detail_recharge_onlines',
            'object' => null,
            'introduction' => '账户【进账】记录详情-在线充值【支付宝，网银】详情表',
        ],
        'us_recharge_pos' => [
            'database' => 'eduwork',
            'string' => 'parent_account_record_detail_recharge_pos',
            'object' => ParentAccountRecordDetailRechargePosModel::class,
            'introduction' => '账户【进账】记录详情-线下充值【POS】详情表',
        ],
        'us_recharge_xuefeibao' => [
            'database' => 'eduwork',
            'string' => 'parent_account_record_detail_recharge_xuefeibao',
            'object' => ParentAccountRecordDetailRechargeXuefeibaoModel::class,
            'introduction' => '账户【进账】记录详情-线上充值【学费宝】详情表',
        ],
        'us_recharge_qrcode_logs' => [
            'database' => 'eduwork',
            'string' => 'parent_account_record_detail_recharge_qrcode_logs',
            'object' => null,
            'introduction' => '账户【进账】记录详情-线下充值【二维码】-支付前请求日志表',
        ],
        'us_recharge_qrcodes' => [
            'database' => 'eduwork',
            'string' => 'parent_account_record_detail_recharge_qrcodes',
            'object' => ParentAccountRecordDetailRechargeQrcodesModel::class,
            'introduction' => '账户【进账】记录详情-线下充值【二维码】详情表',
        ],
        'us_recharge_refunds' => [
            'database' => 'eduwork',
            'string' => 'parent_account_record_detail_recharge_refunds',
            'object' => ParentAccountRecordDetailRechargeRefundsModel::class,
            'introduction' => '账户【进账】记录详情-退【班，考勤】退费】详情表',
        ],
        'us_recharge_weixins' => [
            'database' => 'eduwork',
            'string' => 'parent_account_record_detail_recharge_weixins',
            'object' => ParentAccountRecordDetailRechargeWeixinModel::class,
            'introduction' => '账户【进账】记录详情-线下充值【微信】详情表',
        ],
        'us_recharges' => [
            'database' => 'eduwork',
            'string' => 'parent_account_record_detail_recharges',
            'object' => ParentAccountRecordDetailRechargesModel::class,
            'introduction' => '账户【进账】记录详情',
        ],
        'us_psm_accounts' => [
            'database' => 'eduwork',
            'string' => 'parent_account_student_merchants',
            'object' => ParentAccountStudentMerchantsModel::class,
            'introduction' => '家长学员机构账户表',
        ],
        'us_mp_nexus' => [
            'database' => 'eduwork',
            'string' => 'uc_merchant_parent',
            'object' => MerchantParentModel::class,
            'introduction' => '商家家长关系表',
        ],
        'us_ms_nexus' => [
            'database' => 'eduwork',
            'string' => 'uc_merchant_student',
            'object' => MerchantStudent::class,
            'introduction' => '商家学员关系表',
        ],
        'us_student_communicates' => [
            'database' => 'eduwork',
            'string' => 'us_student_communicates',
            'object' => null,
            'introduction' => '意向客户沟通记录表',
        ],
        'us_ms_transfer_campus' => [
            'database' => 'eduwork',
            'string' => 'uc_merchant_student_transfer_campus',
            'object' => null,
            'introduction' => '商家学员转校区记录表',
        ],
        'us_student_examinations' => [
            'database' => 'eduwork',
            'string' => 'tc_student_examinations',
            'object' => null,
            'introduction' => '学员考试成绩表（爱学考试成绩）',
        ],
        'us_auditions' => [
            'database' => 'eduwork',
            'string' => 'mc_auditions',
            'object' => null,
            'introduction' => '预约试听课表',
        ],
        'us_referral_networks' => [
            'database' => 'eduwork',
            'string' => 'mc_referral_network',
            'object' => ClueActivityModel::class,
            'introduction' => '商家转介绍网络',
        ],

        // 课耗。
        'kh_make_ups' => [
            'database' => 'eduwork',
            'string' => 'bc_make_ups',
            'object' => MakeUpsModel::class,
            'introduction' => '学员补课记录',
        ],
        'kh_attendance_rolls' => [
            'database' => 'eduwork',
            'string' => 'fc_attendance_rolls',
            'object' => AttendanceRollsModel::class,
            'introduction' => '考勤【滚动班】表',
        ],
        'kh_attendances' => [
            'database' => 'eduwork',
            'string' => 'fc_attendances',
            'object' => AttendancesModel::class,
            'introduction' => '考勤表',
        ],
        'kh_attendance_logs' => [
            'database' => 'eduwork',
            'string' => 'uc_parent_attendance_logs',
            'object' => null,
            'introduction' => '家长考勤日志表',
        ],
        'kh_attendance_lives' => [
            'database' => 'eduwork',
            'string' => 'fc_attendance_lives',
            'object' => null,
            'introduction' => '考勤【云课堂直播】表',
        ],

        // 线索块。
        'xs_merchant_parents' => [
            'database' => 'eduwork',
            'string' => 'bc_clue_communicate_merchant_parents',
            'object' => ClueCommunicateMerchantParentModel::class,
            'introduction' => '提现申请记录日志表',
        ],
        'xs_parent_activities' => [
            'database' => 'eduwork',
            'string' => 'bc_clue_parent_activities',
            'object' => null,
            'introduction' => '线索-家长-家长活动报名',
        ],
        'xs_parent_auditions' => [
            'database' => 'eduwork',
            'string' => 'bc_clue_parent_auditions',
            'object' => null,
            'introduction' => '线索-家长-预约试听表',
        ],
        'xs_parent_inputs' => [
            'database' => 'eduwork',
            'string' => 'bc_clue_parent_inputs',
            'object' => ClueParentInputModel::class,
            'introduction' => '线索-家长-商家手动录入',
        ],
        'xs_clue_parents' => [
            'database' => 'eduwork',
            'string' => 'bc_clue_parents',
            'object' => null,
            'introduction' => '线索-家长表【家长线索主表】',
        ],
        'xs_communications' => [
            'database' => 'eduwork',
            'string' => 'mc_communications',
            'object' => null,
            'introduction' => '线索-市场招生沟通记录表',
        ],
        'xs_history_hears' => [
            'database' => 'eduwork',
            'string' => 'mc_history_hears',
            'object' => null,
            'introduction' => '试听记录表',
        ],
        'xs_history_imports' => [
            'database' => 'eduwork',
            'string' => 'mc_history_imports',
            'object' => null,
            'introduction' => '数据导入表',
        ],
        'xs_history_receives' => [
            'database' => 'eduwork',
            'string' => 'mc_history_receives',
            'object' => null,
            'introduction' => '领取分配记录表',
        ],
        'xs_history_recoverys' => [
            'database' => 'eduwork',
            'string' => 'mc_history_recoverys',
            'object' => null,
            'introduction' => '线索回收记录表',
        ],
        'xs_history_schools' => [
            'database' => 'eduwork',
            'string' => 'mc_history_schools',
            'object' => null,
            'introduction' => '市场招生就读学校记录',
        ],
        'xs_history_tostores' => [
            'database' => 'eduwork',
            'string' => 'mc_history_tostores',
            'object' => null,
            'introduction' => '邀约到店记录表',
        ],
        'xs_parent_market_infos' => [
            'database' => 'eduwork',
            'string' => 'mc_parent_market_infos',
            'object' => ParentMarketInfoModel::class,
            'introduction' => '市场招生基本信息表(线索子表)',
        ],
        'xs_parent_markets' => [
            'database' => 'eduwork',
            'string' => 'mc_parent_markets',
            'object' => null,
            'introduction' => '市场招生家长联系表',
        ],
        'xs_parents' => [
            'database' => 'eduwork',
            'string' => 'mc_parents',
            'object' => StudentCluesModel::class,
            'introduction' => '市场招生主线索',
        ],
        'xs_student_clues' => [
            'database' => 'eduwork',
            'string' => 'uc_student_clues',
            'object' => null,
            'introduction' => '招生线索记录表',
        ],
        'xs_signups' => [
            'database' => 'eduwork',
            'string' => 'at_cms_signup',
            'object' => null,
            'introduction' => 'CMS 注册报名表',
        ],

        // 进销存。
        'jxc_collect_serials' => [
            'database' => 'eduwork',
            'string' => 'gc_goods_collect_serials',
            'object' => GoodsCollectSerialsModel::class,
            'introduction' => '商家教学用品入库流水表',
        ],

        // 活动。
        'hd_member_goods' => [
            'database' => 'eduwork',
            'string' => 'bc_distribution_member_goods',
            'object' => null,
            'introduction' => '分销会员和商品关系表',
        ],
        'hd_draws' => [
            'database' => 'eduwork',
            'string' => 'gc_activity_draws',
            'object' => null,
            'introduction' => '抽奖概率表',
        ],
        'hd_lotterys' => [
            'database' => 'eduwork',
            'string' => 'gc_activity_lotterys',
            'object' => null,
            'introduction' => '兑奖码表',
        ],
        'hd_question_relations' => [
            'database' => 'eduwork',
            'string' => 'gc_activity_question_relations',
            'object' => null,
            'introduction' => '活动题库关系表',
        ],
        'hd_questions' => [
            'database' => 'eduwork',
            'string' => 'gc_activity_questions',
            'object' => null,
            'introduction' => '题库表',
        ],
        'hd_spokesmans' => [
            'database' => 'eduwork',
            'string' => 'gc_activity_spokesmans',
            'object' => null,
            'introduction' => '活动代言人表',
        ],
        'hd_subjects' => [
            'database' => 'eduwork',
            'string' => 'gc_activity_subjects',
            'object' => null,
            'introduction' => '题目表',
        ],
        'hd_browses' => [
            'database' => 'eduwork',
            'string' => 'gc_goods_activity_browses',
            'object' => null,
            'introduction' => '活动浏览记录',
        ],
        'hd_posted_ads' => [
            'database' => 'eduwork',
            'string' => 'gc_posted_ads',
            'object' => null,
            'introduction' => '贴广告表',
        ],
        'hd_tuition_activity_logs' => [
            'database' => 'eduwork',
            'string' => 'uc_save_tuition_activity_logs',
            'object' => null,
            'introduction' => '攒学费活动日志表',
        ],
        'hd_activities' => [
            'database' => 'eduwork',
            'string' => 'gc_goods_activities',
            'object' => null,
            'introduction' => '商品【活动】表',
        ],
        'hd_market_activitys' => [
            'database' => 'eduwork',
            'string' => 'mc_market_activitys',
            'object' => null,
            'introduction' => '市场活动表表',
        ],

        // 数据统计。
        'sjtj_expenses' => [
            'database' => 'eduwork',
            'string' => 'fc_expenses',
            'object' => null,
            'introduction' => '商家财务支出表',
        ],
        'sjtj_campus_statistics' => [
            'database' => 'eduwork',
            'string' => 'gc_campus_statistics',
            'object' => null,
            'introduction' => '校区相关数据统计表',
        ],
        'sjtj_mp_flows' => [
            'database' => 'eduwork',
            'string' => 'bi_merchant_parent_flows',
            'object' => BiMerchantParentFlowsModel::class,
            'introduction' => '商家家长流水表',
        ],
        'sjtj_otms_statistics' => [
            'database' => 'eduwork',
            'string' => 'bi_order_class_otms_statistics',
            'object' => OrderClassOtmsStatisticsmModel::class,
            'introduction' => '小班订单统计表',
        ],
        'sjtj_po_statistics' => [
            'database' => 'eduwork',
            'string' => 'bi_parent_order_statistics',
            'object' => null,
            'introduction' => '用户订单统计表',
        ],
        'sjtj_resignup_otms' => [
            'database' => 'eduwork',
            'string' => 'bi_resignup_rate_goods_class_otms',
            'object' => ResignupRateGoodsClassOtmModel::class,
            'introduction' => '续报率表【班级】',
        ],
        'sjtj_resignup_transform_otms' => [
            'database' => 'eduwork',
            'string' => 'bi_resignup_transform_rate_goods_class_otms',
            'object' => ResignupTransformRateGoodsClassOtmModel::class,
            'introduction' => '续报/转化率表【班级】',
        ],
        'sjtj_signup_statistics' => [
            'database' => 'eduwork',
            'string' => 'bi_sign_up_statistics',
            'object' => null,
            'introduction' => '按天统计报名相关数据',
        ],
        'sjtj_teacher_consume_statistics' => [
            'database' => 'eduwork',
            'string' => 'bi_teacher_consume_statistics',
            'object' => null,
            'introduction' => '按天统计教师课耗',
        ],
        'sjtj_cms_sales_services' => [
            'database' => 'eduwork',
            'string' => 'at_cms_sales_service',
            'object' => null,
            'introduction' => '售后服务',
        ],

        // 日志。
        'rz_cms_flows' => [
            'database' => 'eduwork',
            'string' => 'at_cms_flow',
            'object' => null,
            'introduction' => 'CMS 日志表',
        ],

        // 加盟
        'jm_version_template_data' => [
            'database'     => 'eduwork',
            'string'       => 'bc_merchant_league_version_template_datas',
            'object'       => MerchantLeagueVersionTemplateDataModel::class,
            'introduction' => '品牌商版本模板数据',
        ],
        // 全日制课程（收费方案）
        'qrz_course_qrzs' => [
            'database'     => 'eduwork',
            'string'       => 'gc_course_qrzs',
            'object'       => CourseQrzModel::class,
            'introduction' => '全日制课程',
        ],
        'sp_goods_class_qrzs' => [
            'database' => 'eduwork',
            'string' => 'gc_goods_class_qrzs',
            'object' => GoodsClassQrzModel::class,
            'introduction' => '班级【全日制】表',
        ],
        'amount_item_qrzs' => [
            'database'     => 'eduwork',
            'string'       => 'gc_amount_item_qrzs',
            'object'       => AmountItemQrzModel::class,
            'introduction' => '全日制费用项表',
        ],
        'kh_attendance_qrzs' => [
            'database'     => 'eduwork',
            'string'       => 'fc_attendance_qrzs',
            'object'       => AttendanceQrzModel::class,
            'introduction' => '全日制考勤表',
        ],
        'lesson_rule_qrzs' => [
            'database'     => 'eduwork',
            'string'       => 'gc_lesson_rule_qrzs',
            'object'       => LessonRuleQrzModel::class,
            'introduction' => '全日制规则表',
        ],
        'lesson_rule_qrz_detail_qrzs' => [
            'database'     => 'eduwork',
            'string'       => 'gc_lesson_rule_qrz_details',
            'object'       => LessonRuleDetailQrzModel::class,
            'introduction' => '全日制规则详情表',
        ],
        'lesson_rule_qrz_detail_datas_qrz' => [
            'database'     => 'eduwork',
            'string'       => 'gc_lesson_rule_qrz_detail_datas',
            'object'       =>  LessonRuleDetailDataQrzModel::class,
            'introduction' => '全日制规则详情数据表',
        ],
        'lesson_qrzs' => [
            'database'     => 'eduwork',
            'string'       => 'gc_lesson_qrzs',
            'object'       => LessonQrzsModel::class,
            'introduction' => '全日制班级课次表',
        ],
        'dd_parent_course_qrzs' => [
            'database' => 'eduwork',
            'string' => 'parent_account_record_detail_order_course_qrzs',
            'object' => ParentAccountRecordDetailOrderCourseQrzModel::class,
            'introduction' => '订单详情表【课程-全日制课程详情】',
        ],
        'dd_parent_course_qrz_details' => [
            'database' => 'eduwork',
            'string' => 'parent_account_record_detail_order_course_qrz_details',
            'object' => ParentAccountRecordDetailOrderCourseDetailQrzModel::class,
            'introduction' => '订单详情表【课程-全日制课程详情】',
        ],
        'dd_parent_class_qrzs' => [
            'database' => 'eduwork',
            'string' => 'parent_account_record_detail_order_class_qrzs',
            'object' => ParentAccountRecordDetailOrderClassQrzModel::class,
            'introduction' => '订单详情表【班级-全日制报名详情】',
        ],
        'ywpz_config_merchant_refund_qrzs' => [
            'database' => 'eduwork',
            'string' => 'bc_config_merchant_refund_qrzs',
            'object' => ConfigMerchantRefundQrzModel::class,
            'introduction' => '全日制退费机制表',
        ],
        //2019-01-29 liuyulong v5.3.3新增两张表 开始
        'ywpz_config_merchant_seasons' => [
            'database' => 'eduwork',
            'string' => 'bc_config_merchant_seasons',
            'object' => ConfigMerchantSeasonModel::class,
            'introduction' => '商家配置学期表',
        ],
        'ywpz_config_merchant_resignups' => [
            'database' => 'eduwork',
            'string' => 'bc_config_merchant_resignups',
            'object' => ConfigMerchantResignupModel::class,
            'introduction' => '商家配置续报表',
        ],
        //2019-01-29 liuyulong v5.3.3新增两张表 结束
        'ywpz_config_merchant_transfer_classes' => [
            'database' => 'eduwork',
            'string' => 'bc_config_merchant_transfer_classes',
            'object' => ConfigMerchantTransferClassModel::class,
            'introduction' => '商家转班配置表',
        ],
        'jxc_goods_transfer_price_records' => [
            'database' => 'eduwork',
            'string' => 'bc_goods_transfer_price_records',
            'object' => GoodsPriceRecordsModel::class,
            'introduction' => '商品调价记录表',
        ],
        'jxc_goods_campus_output_records' => [
            'database' => 'eduwork',
            'string' => 'bc_goods_campus_output_records',
            'object' => GoodsCampusOutputModel::class,
            'introduction' => '商品校区出库记录表',
        ],
        'sp_gc_course_types' => [
            'database' => 'eduwork',
            'string' => 'gc_course_types',
            'object' => CourseTypesModel::class,
            'introduction' => '课程类型表',
        ],
        // 优惠券
        'yh_discount_merchant_coupons' => [
            'database' => 'eduwork',
            'string' => 'bc_discount_merchant_coupons',
            'object' => CouponsModel::class,
            'introduction' => '商家优惠券批次',
        ],
        'yh_discount_merchant_coupon_attachments' => [
            'database' => 'eduwork',
            'string' => 'bc_discount_merchant_coupon_attachments',
            'object' => CouponAttachmentsModel::class,
            'introduction' => '商家优惠券批次附件',
        ],
        'yh_discount_merchant_coupon_releases' => [
            'database' => 'eduwork',
            'string' => 'bc_discount_merchant_coupon_releases',
            'object' => CouponReleasesModel::class,
            'introduction' => '商家优惠券',
        ],
        'yh_discount_merchant_coupon_applys' => [
            'database' => 'eduwork',
            'string' => 'bc_discount_merchant_coupon_applys',
            'object' => CouponApplysModel::class,
            'introduction' => '商家优惠券申请记录',
        ],
        'yh_discount_merchant_coupon_apply_details' => [
            'database' => 'eduwork',
            'string' => 'bc_discount_merchant_coupon_apply_details',
            'object' => CouponApplyDetailsModel::class,
            'introduction' => '商家优惠券发放申请详情表',
        ],
        'yh_discount_merchant_calculate_rules' => [
            'database' => 'eduwork',
            'string' => 'bc_discount_merchant_calculate_rules',
            'object' =>DiscountRulesModel::class,
            'introduction' => '商家优惠计算规则',
        ],
        'su_mc_employee_setups' => [
            'database' => 'eduwork',
            'string' => 'mc_employee_setups',
            'object' => EmployeeSetupModel::class,
            'introduction' => '员工设置表',
        ],
        'us_im_group' => [
            'database' => 'eduwork',
            'string' => 'bc_im_group_members',
            'object' => ImGroupMembersModel::class,
            'introduction' => 'IM群成员表',
        ],
    ],

    // 日志库。
    'edulogs' => [
        'push_message_logs' => [
            'database' => 'edulogs',
            'string' => 'bc_push_message_logs',
            'object' => null,
            'introduction' => 'APP推送消息日志表',
        ],
        'emp_login_logs' => [
            'database' => 'edulogs',
            'string' => 'ec_login_logs',
            'object' => null,
            'introduction' => '员工登录日志',
        ],
        'operation_logs' => [
            'database' => 'edulogs',
            'string' => 'sc_functional_operation_number_logs',
            'object' => null,
            'introduction' => '功能操作次数日志表',
        ],
        'version_release_records' => [
            'database' => 'edulogs',
            'string' => 'sc_version_release_records',
            'object' => null,
            'introduction' => '版本发布记录',
        ],
        'parent_login_logs' => [
            'database' => 'edulogs',
            'string' => 'uc_login_logs',
            'object' => null,
            'introduction' => '家长登录日志',
        ],
        'cms_login_logs' => [
            'database' => 'edulogs',
            'string' => 'at_cms_login_log',
            'object' => null,
            'introduction' => 'CMS登录日志表',
        ],
        'cms_operation_logs' => [
            'database' => 'edulogs',
            'string' => 'at_cms_operate_log',
            'object' => null,
            'introduction' => '操作日志表',
        ],
    ],
];