<?php

namespace app\admin\controller;

use think\Controller;
use think\Db;
class Base extends Controller
{
    //初始化
    public function initialize()
    {
        //parent::initialize(); // TODO: Change the autogenerated stub
        if (!session('?admin.id')) {
            $this->redirect('admin/index/login');

        }

    }

    //获取医院属性
    public function getType() {
          $res = Db::name('hospital_type')->select();
          return $res;

    }

    //获取公私属性
    public function getPublic() {
        $res =   Db::name('hospital_public')->select();
        return $res;
}
    //三级联动
    public function getArea() {
        $res = Db::name('area')->where('parent_code=" "')->select();
        return $res;
    }
}
