<?php

namespace app\admin\controller;

use app\common\model\Admin;

use think\Controller;
use think\facade\Request;
use think\facade\Session;

class Index extends Controller
{
    //重复登录过滤
    public function initialize()
    {
        //parent::initialize(); // TODO: Change the autogenerated stub
        if (session('?admin.id')) {
            $this->redirect('admin/home/index');

        }

    }
    //后台登录
    public function login() {
        if(Request::isAjax()) {
            $data = [
               'username' => input('post.username'),
                'password'=> input('post.password')
            ];
            $admin = new Admin();
            $result = $admin->login($data);
            if ($result == 1) {
                $this->success('登录成功','admin/home/index');
            } else {
                $this->error($result);
            }
        }

        return $this->fetch();
    }

    //注册
    public function register() {
        if (Request::isAjax()) {
            $data = [
                'username'  =>  input('post.username'),
                'password'  =>  input('post.password'),
                'conpass'   =>  input('post.conpass'),
                'nickname'  =>  input('post.nickname'),
                'email'     =>  input('post.email')
            ];
            $admin = new Admin();
            $result = $admin->register($data);
            if ($result == 1) {
                $this->success('注册成功','admin/index/login');
            } else {
                $this->error($result);
            }
        }
        return $this->fetch();
    }

    //找回密码
    public function forget() {
        if (Request::isAjax()) {
            $code = mt_rand(1000,9999);
            session('code',$code);
            $result = sendEmail(input('post.email'),'重置密码验证码','你的验证码是'.$code);
            $this->success('验证码发送成功');
            if ($result) {
               $this->success('验证码发送成功');

           } else {
               $this->error('验证码发送失败');
           }
        }
        return $this->fetch();
    }

    //重置密码
    public function reset() {
        $data = [
            'code' => input('post.code'),
            'email' => input('post.email')
        ];

        $result = model('Admin')->reset($data);

        if ($result == 1) {
            $this->success('重置密码成功，请去邮箱查找','admin/index/login');
        } else {
            $this->error($result);
        }

    }
}
