<?php
/**
 * Created by PhpStorm.
 * User: 15691
 * Date: 2020/4/3
 * Time: 17:10
 */

namespace app\index\model;


use think\Model;

class User extends Model
{
    //protected $pk = 'loginip'; //设置主键

  //  protected $table = 'hd_role'; //设置其他表

    //初始化模型方法
    protected  static function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        echo '初始化模型方法'."<br>";
    }

    public function getPwd() {
     // return self::where('username','dvd')->find()->password;
      return self::where('username','dvd')->find()->getAttr('username');
    }

    //创建获取器
    public function getStatusAttr($value) {
        $arr = [
            -1 => '禁用',
            0 => '审核中',
            1 => '正常'
        ];
        return $arr[$value];
    }

    //创建一个虚拟获取器，可以对多个字段进行过滤
    public function getNothingAttr($value,$data) {
        $arr = [
            -1 => '禁用',
            0 => '审核中',
            1 => '正常'
        ];
        return $arr[$data['status']];
    }

    //创建一个搜索器
    public function  searchEmailAttr($query,$value) {
        $query->where('email','like',$value.'%');
    }

    //创建一个限定时间搜索器
    public function searchCreateAtAttr($query,$value) {
        $query->whereBetweenTime('create_at',$value[0],$value[1]);
    }

}