<?php
namespace app\index\controller;

use think\Controller;
use think\Env;

class Index extends Controller
{
    protected function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        echo 'init';
    }

    public function index()
    {
        //dump(\think\facade\Env::get());
        //dump($_SERVER["HTTP_REFERER"]);  //$_SERVER['HTTP_REFERER'] 将很容易得到链接到当前页面的前一页面的地址
        }

    public function hello($name = 'ThinkPHP5')
    {
        return 'hello,' . $name;
    }
    public function arr() {
        $arr = [1,2,3];
        //return $arr;
        return json($arr);
    }
    public function tmp() {
        return view();
    }
}
